# Basic Netlify configuration file

[build]
  command = "npm run build"
  publish = "./"

[dev]
  # Optional but good practice: Explicitly tell the dev server the same info.
  publish = "."
  functions = "netlify/functions"