# Basic Netlify configuration file

[build]
  # Specifies the directory Netlify builds from and deploys.
  # "./node_modules/.bin/tailwindcss" ensures the local installation is used.
  command = "./node_modules/.bin/tailwindcss build -o ./dist/tailwind.css"
  publish = "./dist"
  # Specifies where your Netlify Functions live.
  functions = "netlify/functions"

[dev]
  # Optional but good practice: Explicitly tell the dev server the same info.
  publish = "."
  functions = "netlify/functions"